<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'slug'        => 'riz-blanc-premium-5kg',
                'title'       => 'Riz Blanc Premium 5kg',
                'category'    => 'Riz Blanc',
                'image'       => '/assets/img/riz2.jpeg',
                'images'      => ['/assets/img/riz2.jpeg', '/assets/img/riz1.jpeg', '/assets/img/riz3.jpeg'],
                'price'       => 5000,
                'price_promo' => 6000,
                'discount'    => 17,
                'badge'       => 'Promo',
                'stars'       => 5,
                'reviews'     => 24,
                'in_stock'    => true,
                'short'       => 'Riz blanc naturellement parfumé, certifié ITRA, cultivé par nos 30 producteurs de Tagbega.',
                'description' => 'Notre riz blanc premium est le résultat d\'un travail minutieux : sélection des meilleures parcelles, récolte au moment optimal, transformation dans nos installations modernes et certification ITRA. Chaque grain est entier, blanc brillant, avec un taux de brisure inférieur à 5%. Idéal pour toutes les préparations culinaires africaines et internationales.',
                'details'     => [
                    ['label' => 'Poids net',       'value' => '5 kg'],
                    ['label' => 'Type',            'value' => 'Riz Blanc Décortiqué'],
                    ['label' => 'Certification',   'value' => 'ITRA (Institut Togolais de Recherche Agronomique)'],
                    ['label' => 'Origine',         'value' => 'Tagbega, Région des Plateaux, TOGO'],
                    ['label' => 'Conservation',    'value' => '6 mois — lieu frais et sec'],
                    ['label' => 'Conditionnement', 'value' => 'Sac hermétique refermable'],
                    ['label' => 'Taux de brisure', 'value' => '< 5%'],
                ],
                'features'    => ['100% Naturel', 'Sans OGM', 'Certifié ITRA', 'Traçable'],
            ],
            [
                'slug'        => 'riz-etuve-local-5kg',
                'title'       => 'Riz Étuvé Local 5kg',
                'category'    => 'Riz Étuvé',
                'image'       => '/assets/img/riz3.jpeg',
                'images'      => ['/assets/img/riz3.jpeg', '/assets/img/riz5.jpeg', '/assets/img/riz1.jpeg'],
                'price'       => 5500,
                'price_promo' => 6500,
                'discount'    => 15,
                'badge'       => 'Promo',
                'stars'       => 5,
                'reviews'     => 18,
                'in_stock'    => true,
                'short'       => 'Riz étuvé à la vapeur selon le procédé traditionnel, grains fermes et nutritifs, certifié ITRA.',
                'description' => 'Le riz étuvé HEZOUWE passe par un processus de précuisson à la vapeur avant décorticage, qui emprisonne les nutriments dans le grain. Résultat : un riz plus ferme à la cuisson, plus riche en vitamines B et en minéraux, et qui tient mieux après cuisson. Parfait pour les plats mijotés, les riz sautés et les recettes traditionnelles togolaises.',
                'details'     => [
                    ['label' => 'Poids net',        'value' => '5 kg'],
                    ['label' => 'Type',             'value' => 'Riz Étuvé Précuit Vapeur'],
                    ['label' => 'Certification',    'value' => 'ITRA'],
                    ['label' => 'Origine',          'value' => 'Tagbega, Région des Plateaux, TOGO'],
                    ['label' => 'Conservation',     'value' => '6 mois — lieu frais et sec'],
                    ['label' => 'Temps de cuisson', 'value' => '20–25 min'],
                    ['label' => 'Valeur nutritive', 'value' => 'Riche en vitamines B1, B3'],
                ],
                'features'    => ['Riche en Nutriments', 'Ferme à Cuisson', 'Certifié ITRA', 'Traçable'],
            ],
            [
                'slug'        => 'riz-itra-certifie-10kg',
                'title'       => 'Riz ITRA Certifié 10kg',
                'category'    => 'Riz Certifié',
                'image'       => '/assets/img/riz5.jpeg',
                'images'      => ['/assets/img/riz5.jpeg', '/assets/img/riz2.jpeg', '/assets/img/riz6.jpeg'],
                'price'       => 7000,
                'price_promo' => 8500,
                'discount'    => 18,
                'badge'       => 'Bestseller',
                'stars'       => 5,
                'reviews'     => 41,
                'in_stock'    => true,
                'short'       => 'Notre format 10kg idéal pour les familles nombreuses et les petits revendeurs, double certification qualité.',
                'description' => 'Le Riz ITRA Certifié 10kg est notre format le plus populaire auprès des ménages et des petits commerçants. Il offre le meilleur rapport qualité-prix de notre gamme, avec la garantie d\'une double vérification qualité par notre équipe et par les laboratoires de l\'ITRA. Chaque lot porte un numéro de traçabilité unique.',
                'details'     => [
                    ['label' => 'Poids net',     'value' => '10 kg'],
                    ['label' => 'Type',          'value' => 'Riz Blanc Certifié'],
                    ['label' => 'Certification', 'value' => 'Double Certification ITRA'],
                    ['label' => 'Origine',       'value' => 'Tagbega, Région des Plateaux, TOGO'],
                    ['label' => 'Conservation',  'value' => '6 mois — lieu frais et sec'],
                    ['label' => 'Traçabilité',   'value' => 'Numéro de lot sur chaque sac'],
                ],
                'features'    => ['Double Certification', 'Meilleur Prix/kg', 'Bestseller', 'Traçable'],
            ],
            [
                'slug'        => 'balles-son-riz-5kg',
                'title'       => 'Balles & Son de Riz 5kg',
                'category'    => 'Sous-Produits',
                'image'       => '/assets/img/riz5.jpeg',
                'images'      => ['/assets/img/riz5.jpeg', '/assets/img/riz1.jpeg', '/assets/img/image12.jpg'],
                'price'       => 2000,
                'price_promo' => 2500,
                'discount'    => 20,
                'badge'       => 'Éco',
                'stars'       => 4,
                'reviews'     => 9,
                'in_stock'    => true,
                'short'       => 'Sous-produits de transformation du riz : balles et son, idéaux pour l\'alimentation animale et le compostage.',
                'description' => 'Les balles et son de riz sont les sous-produits naturels issus du décorticage du riz paddy. Riches en fibres, en silice et en nutriments, ils sont utilisés pour l\'alimentation animale (volailles, bovins), comme matériau d\'isolation thermique, combustible pour les brûleurs à biomasse, ou amendement organique pour les sols agricoles.',
                'details'     => [
                    ['label' => 'Poids net',    'value' => '5 kg'],
                    ['label' => 'Type',         'value' => 'Balles & Son de Riz'],
                    ['label' => 'Usage',        'value' => 'Alimentation animale, compostage, biomasse'],
                    ['label' => 'Origine',      'value' => 'Tagbega, TOGO'],
                    ['label' => 'Conservation', 'value' => '3 mois — lieu sec'],
                ],
                'features'    => ['Sous-produit Naturel', 'Alimentation Animale', 'Compostable', 'Économique'],
            ],
            [
                'slug'        => 'riz-blanc-bulk-25kg',
                'title'       => 'Riz Blanc Bulk 25kg',
                'category'    => 'Riz Blanc',
                'image'       => '/assets/img/riz6.jpeg',
                'images'      => ['/assets/img/riz6.jpeg', '/assets/img/riz2.jpeg', '/assets/img/riz1.jpeg'],
                'price'       => 10000,
                'price_promo' => 12000,
                'discount'    => 17,
                'badge'       => 'Pro',
                'stars'       => 5,
                'reviews'     => 32,
                'in_stock'    => true,
                'short'       => 'Format 25kg pour revendeurs et restaurateurs, meilleur prix au kilo de toute notre gamme.',
                'description' => 'Le sac de 25kg est notre format professionnel, conçu pour les revendeurs, les restaurants, les cantines scolaires et les institutions. Il offre le meilleur rapport qualité-prix de toute notre gamme. Disponible en riz blanc et riz étuvé, avec conditionnement renforcé anti-humidité.',
                'details'     => [
                    ['label' => 'Poids net',       'value' => '25 kg'],
                    ['label' => 'Type',            'value' => 'Riz Blanc Décortiqué Bulk'],
                    ['label' => 'Certification',   'value' => 'ITRA'],
                    ['label' => 'Origine',         'value' => 'Tagbega, TOGO'],
                    ['label' => 'Conservation',    'value' => '6 mois — lieu frais et sec'],
                    ['label' => 'Conditionnement', 'value' => 'Sac renforcé anti-humidité'],
                    ['label' => 'Cible',           'value' => 'Revendeurs, restaurants, institutions'],
                ],
                'features'    => ['Format Pro', 'Meilleur Prix/kg', 'Certifié ITRA', 'Livraison Groupée'],
            ],
            [
                'slug'        => 'riz-etuve-bulk-25kg',
                'title'       => 'Riz Étuvé Bulk 25kg',
                'category'    => 'Riz Étuvé',
                'image'       => '/assets/img/riz7.jpeg',
                'images'      => ['/assets/img/riz7.jpeg', '/assets/img/riz3.jpeg', '/assets/img/riz5.jpeg'],
                'price'       => 11000,
                'price_promo' => 13000,
                'discount'    => 15,
                'badge'       => 'Pro',
                'stars'       => 5,
                'reviews'     => 21,
                'in_stock'    => true,
                'short'       => 'Format 25kg de riz étuvé pour professionnels, idéal pour les restaurants et les commandes institutionnelles.',
                'description' => 'Notre riz étuvé bulk 25kg est la solution idéale pour les professionnels de la restauration qui recherchent un riz ferme et savoureux en grande quantité. Le processus d\'étuvage garantit un riz qui tient bien à la cuisson, ne colle pas et conserve toutes ses propriétés nutritionnelles.',
                'details'     => [
                    ['label' => 'Poids net',        'value' => '25 kg'],
                    ['label' => 'Type',             'value' => 'Riz Étuvé Bulk'],
                    ['label' => 'Certification',    'value' => 'ITRA'],
                    ['label' => 'Origine',          'value' => 'Tagbega, TOGO'],
                    ['label' => 'Temps de cuisson', 'value' => '20–25 min'],
                    ['label' => 'Conservation',     'value' => '6 mois — lieu frais et sec'],
                ],
                'features'    => ['Format Restauration', 'Ferme à Cuisson', 'Certifié ITRA', 'Anti-Gaspillage'],
            ],
            [
                'slug'        => 'graines-riz-premium-1kg',
                'title'       => 'Graines de Riz Premium 1kg',
                'category'    => 'Graines',
                'image'       => '/assets/img/riz8.jpeg',
                'images'      => ['/assets/img/riz8.jpeg', '/assets/img/riz1.jpeg', '/assets/img/riz2.jpeg'],
                'price'       => 3000,
                'price_promo' => 4000,
                'discount'    => 25,
                'badge'       => 'Nouveau',
                'stars'       => 5,
                'reviews'     => 7,
                'in_stock'    => true,
                'short'       => 'Graines de riz sélectionnées pour la plantation, variétés à haut rendement validées par l\'ITRA.',
                'description' => 'Nos graines de riz premium sont issues des meilleures variétés sélectionnées par l\'ITRA pour leur rendement élevé, leur résistance aux maladies et leur adaptation aux conditions climatiques du TOGO. Idéales pour les producteurs souhaitant améliorer leur culture.',
                'details'     => [
                    ['label' => 'Poids net',           'value' => '1 kg (environ 40 000 graines)'],
                    ['label' => 'Type',                'value' => 'Semences Sélectionnées'],
                    ['label' => 'Taux de germination', 'value' => '> 90%'],
                    ['label' => 'Validation',          'value' => 'ITRA'],
                    ['label' => 'Superficie couverte', 'value' => 'Environ 500 m²'],
                    ['label' => 'Conservation',        'value' => '12 mois — lieu frais et sec'],
                ],
                'features'    => ['Haut Rendement', '> 90% Germination', 'Sélection ITRA', 'Usage Agricole'],
            ],
            [
                'slug'        => 'pack-decouverte-riz',
                'title'       => 'Pack Découverte Riz HEZOUWE',
                'category'    => 'Packs',
                'image'       => '/assets/img/riz2.jpeg',
                'images'      => ['/assets/img/riz2.jpeg', '/assets/img/riz3.jpeg', '/assets/img/riz5.jpeg'],
                'price'       => 8000,
                'price_promo' => 10000,
                'discount'    => 20,
                'badge'       => 'Coup de Cœur',
                'stars'       => 5,
                'reviews'     => 15,
                'in_stock'    => true,
                'short'       => 'Découvrez toute la gamme HEZOUWE : 2kg riz blanc + 2kg riz étuvé + 1kg son de riz dans un coffret.',
                'description' => 'Le Pack Découverte HEZOUWE est le cadeau idéal pour découvrir ou faire découvrir nos produits. Il contient 2kg de riz blanc premium, 2kg de riz étuvé local et 1kg de son de riz, le tout dans un coffret soigneusement présenté avec une fiche de recettes togolaises traditionnelles.',
                'details'     => [
                    ['label' => 'Contenu',       'value' => '2kg Riz Blanc + 2kg Riz Étuvé + 1kg Son'],
                    ['label' => 'Poids total',   'value' => '5 kg'],
                    ['label' => 'Certification', 'value' => 'ITRA (tous les produits inclus)'],
                    ['label' => 'Présentation',  'value' => 'Coffret cadeau avec fiche recettes'],
                    ['label' => 'Origine',       'value' => 'Tagbega, TOGO'],
                    ['label' => 'Idéal pour',    'value' => 'Cadeau, découverte, test de gamme'],
                ],
                'features'    => ['3 Produits en 1', 'Idéal Cadeau', 'Fiche Recettes', 'Certifié ITRA'],
            ],
            [
                'slug'        => 'riz-bio-rare-3kg',
                'title'       => 'Riz Bio Rare 3kg',
                'category'    => 'Riz Certifié',
                'image'       => '/assets/img/riz8.jpeg',
                'images'      => ['/assets/img/riz8.jpeg', '/assets/img/riz1.jpeg', '/assets/img/riz6.jpeg'],
                'price'       => 4500,
                'price_promo' => 5500,
                'discount'    => 18,
                'badge'       => 'Exclusif',
                'stars'       => 5,
                'reviews'     => 11,
                'in_stock'    => true,
                'short'       => 'Variété rare de riz cultivée sans intrants chimiques, production limitée, goût incomparable.',
                'description' => 'Notre Riz Bio Rare est issu de parcelles pilotes cultivées sans aucun intrant chimique, selon les méthodes ancestrales togolaises. Production limitée à quelques centaines de kilogrammes par saison, ce riz se distingue par son arôme unique, sa texture légèrement croquante et sa richesse en micronutriments.',
                'details'     => [
                    ['label' => 'Poids net',    'value' => '3 kg'],
                    ['label' => 'Type',         'value' => 'Riz Biologique — Production Limitée'],
                    ['label' => 'Culture',      'value' => 'Sans intrants chimiques'],
                    ['label' => 'Certification','value' => 'ITRA + Engagement Bio'],
                    ['label' => 'Origine',      'value' => 'Parcelles pilotes, Tagbega, TOGO'],
                    ['label' => 'Conservation', 'value' => '4 mois — lieu frais et sec'],
                    ['label' => 'Production',   'value' => 'Limitée — quelques centaines kg/saison'],
                ],
                'features'    => ['100% Bio', 'Production Limitée', 'Arôme Unique', 'Certifié ITRA'],
            ],
        ];

        foreach ($products as $data) {
            Product::updateOrCreate(
                ['slug' => $data['slug']],
                [
                    'title'       => $data['title'],
                    'category'    => $data['category'],
                    'short'       => $data['short'],
                    'description' => $data['description'],
                    'image'       => $data['image'],
                    'images'      => $data['images'] ?? [],
                    'price'       => $data['price'],
                    'price_promo' => $data['price_promo'] ?? null,
                    'discount'    => $data['discount'] ?? 0,
                    'badge'       => $data['badge'] ?? null,
                    'stars'       => $data['stars'] ?? 5,
                    'reviews'     => $data['reviews'] ?? 0,
                    'in_stock'    => $data['in_stock'] ?? true,
                    'details'     => $data['details'] ?? [],
                    'features'    => $data['features'] ?? [],
                ]
            );
        }

        $this->command->info('  ' . count($products) . ' produits seedés.');
    }
}
