<?php

return [
    [
        'slug'        => 'collecte',
        'title'       => 'Collecte de Riz',
        'icon'        => 'flaticon-eco-friendly',
        'image'       => '/assets/img/riz1.jpeg',
        'image2'      => '/assets/img/inner-page/service/service-details-02.jpg',
        'image3'      => '/assets/img/inner-page/service/service-details-03.jpg',
        'short'       => 'Collecte directe auprès des 30 producteurs partenaires du TOGO pour garantir la qualité et la fraîcheur.',
        'description' => 'Notre service de collecte assure une chaîne d\'approvisionnement directe et transparente entre les 30 producteurs membres de HEZOUWE et nos centres de transformation. Chaque récolte est soigneusement sélectionnée selon des critères stricts de qualité.',
        'description2'=> 'Nous travaillons en étroite collaboration avec les producteurs locaux pour planifier les calendriers de collecte, garantir des prix équitables et assurer que le riz arrive dans les meilleures conditions à nos installations de transformation.',
        'steps' => [
            ['num' => '01', 'title' => 'Évaluation de la récolte', 'text' => 'Inspection visuelle et tests qualité sur le terrain avant toute collecte.'],
            ['num' => '02', 'title' => 'Collecte & Pesage', 'text' => 'Collecte standardisée avec pesage certifié et reçus remis aux producteurs.'],
            ['num' => '03', 'title' => 'Transport Sécurisé', 'text' => 'Acheminement dans des conditions optimales pour préserver la qualité du riz.'],
            ['num' => '04', 'title' => 'Réception au Centre', 'text' => 'Contrôle final à la réception avant stockage et transformation.'],
        ],
        'benefits' => [
            'Prix justes et transparents pour les producteurs',
            'Collecte planifiée selon les saisons de récolte',
            'Traçabilité complète de la ferme à la table',
            'Paiement rapide aux producteurs partenaires',
            'Respect des normes sanitaires lors du transport',
            'Contrôle qualité à chaque étape',
        ],
        'facts' => [
            ['value' => '30+', 'label' => 'Producteurs partenaires'],
            ['value' => '2',   'label' => 'Saisons de récolte / an'],
            ['value' => '100%','label' => 'Riz local togolais'],
        ],
    ],
    [
        'slug'        => 'transformation',
        'title'       => 'Transformation',
        'icon'        => 'flaticon-dairy-products',
        'image'       => '/assets/img/riz5.jpeg',
        'image2'      => '/assets/img/inner-page/service/service-details-01.jpg',
        'image3'      => '/assets/img/inner-page/service/service-details-03.jpg',
        'short'       => 'Transformation du riz brut en riz blanc et étuvé selon les normes ITRA avec équipements modernes.',
        'description' => 'Notre unité de transformation utilise des équipements modernes pour convertir le riz paddy en riz blanc de qualité premium et en riz étuvé. Chaque lot est traité selon un protocole rigoureux garantissant la pureté, le taux de brisure minimal et les propriétés nutritionnelles.',
        'description2'=> 'La transformation comprend le décorticage, le blanchiment, le triage optique et le polissage. Le riz étuvé suit en plus un processus de précuisson à la vapeur qui améliore ses qualités nutritionnelles et sa résistance à la cuisson.',
        'steps' => [
            ['num' => '01', 'title' => 'Nettoyage & Triage', 'text' => 'Élimination des impuretés, pierres et grains défectueux par triage mécanique et optique.'],
            ['num' => '02', 'title' => 'Décorticage', 'text' => 'Retrait de l\'enveloppe extérieure (balle) pour obtenir le riz cargo.'],
            ['num' => '03', 'title' => 'Blanchiment', 'text' => 'Polissage du riz pour obtenir le grain blanc brillant selon les standards de qualité.'],
            ['num' => '04', 'title' => 'Conditionnement', 'text' => 'Ensachage sous contrôle qualité en sacs de 1kg, 5kg, 10kg et 25kg.'],
        ],
        'benefits' => [
            'Équipements modernes certifiés aux normes ITRA',
            'Taux de brisure minimal garanti (< 5%)',
            'Riz blanc et riz étuvé de haute qualité',
            'Capacité de traitement de plusieurs tonnes/jour',
            'Contrôle de qualité à chaque étape du processus',
            'Sous-produits valorisés (son, balles de riz)',
        ],
        'facts' => [
            ['value' => '< 5%', 'label' => 'Taux de brisure'],
            ['value' => '2',    'label' => 'Types de riz produits'],
            ['value' => '95%',  'label' => 'Rendement en riz blanc'],
        ],
    ],
    [
        'slug'        => 'certification',
        'title'       => 'Certification ITRA',
        'icon'        => 'flaticon-broccoli',
        'image'       => '/assets/img/riz3.jpeg',
        'image2'      => '/assets/img/inner-page/service/service-details-01.jpg',
        'image3'      => '/assets/img/inner-page/service/service-details-02.jpg',
        'short'       => 'Certification internationale ITRA garantissant la qualité, la traçabilité et les normes de sécurité alimentaire.',
        'description' => 'La certification ITRA (Institut Togolais de Recherche Agronomique) est le gage de qualité le plus reconnu pour les produits agricoles togolais. HEZOUWE a obtenu cette certification après une évaluation rigoureuse de l\'ensemble de sa chaîne de production.',
        'description2'=> 'Cette certification garantit à nos clients que chaque sac de riz HEZOUWE répond aux normes strictes de qualité alimentaire, de pureté et de sécurité sanitaire. Elle permet également une traçabilité complète du grain depuis la parcelle du producteur jusqu\'au consommateur final.',
        'steps' => [
            ['num' => '01', 'title' => 'Audit des Producteurs', 'text' => 'Inspection des pratiques agricoles et des conditions de culture chez les producteurs membres.'],
            ['num' => '02', 'title' => 'Contrôle du Processus', 'text' => 'Vérification de chaque étape de transformation selon les protocoles ITRA.'],
            ['num' => '03', 'title' => 'Analyses Laboratoire', 'text' => 'Tests de résidus, d\'humidité, de pureté et de valeur nutritionnelle en laboratoire certifié.'],
            ['num' => '04', 'title' => 'Délivrance du Certificat', 'text' => 'Attribution du label ITRA avec numéro de lot et date de certification.'],
        ],
        'benefits' => [
            'Traçabilité complète du producteur au consommateur',
            'Analyses laboratoire régulières et documentées',
            'Respect des normes de sécurité alimentaire internationales',
            'Label reconnu par les institutions togolaises',
            'Renouvellement annuel de la certification',
            'Accès à de nouveaux marchés grâce au label qualité',
        ],
        'facts' => [
            ['value' => 'ITRA', 'label' => 'Certification obtenue'],
            ['value' => '100%','label' => 'Lots certifiés'],
            ['value' => '12',  'label' => 'Contrôles / an'],
        ],
    ],
    [
        'slug'        => 'livraison',
        'title'       => 'Livraison Sécurisée',
        'icon'        => 'flaticon-agriculture',
        'image'       => '/assets/img/riz6.jpeg',
        'image2'      => '/assets/img/inner-page/service/service-details-02.jpg',
        'image3'      => '/assets/img/inner-page/service/service-details-03.jpg',
        'short'       => 'Livraison fiable et rapide de nos produits riz vers le TOGO et l\'Afrique de l\'Ouest avec suivi en temps réel.',
        'description' => 'Notre service de livraison couvre l\'ensemble du territoire togolais et s\'étend vers les pays limitrophes d\'Afrique de l\'Ouest. Nous disposons d\'un réseau logistique fiable assurant des délais de livraison respectés et la préservation de la qualité du produit jusqu\'à destination.',
        'description2'=> 'Chaque livraison est accompagnée d\'un bon de livraison certifié et d\'une attestation de qualité. Nos partenaires logistiques sont sélectionnés pour leur fiabilité et leur respect des normes de transport alimentaire.',
        'steps' => [
            ['num' => '01', 'title' => 'Préparation de la Commande', 'text' => 'Vérification du stock, préparation et étiquetage des colis selon la commande.'],
            ['num' => '02', 'title' => 'Chargement Sécurisé', 'text' => 'Chargement dans des véhicules adaptés au transport alimentaire.'],
            ['num' => '03', 'title' => 'Suivi en Temps Réel', 'text' => 'Notification à chaque étape du transport jusqu\'à la livraison finale.'],
            ['num' => '04', 'title' => 'Livraison & Confirmation', 'text' => 'Remise au destinataire avec signature et confirmation de réception.'],
        ],
        'benefits' => [
            'Livraison dans tout le TOGO sous 48h',
            'Extension vers l\'Afrique de l\'Ouest disponible',
            'Suivi de commande en temps réel',
            'Livraison en gros pour les revendeurs',
            'Conditions de transport adaptées aux denrées alimentaires',
            'Assurance marchandise disponible',
        ],
        'facts' => [
            ['value' => '48h',  'label' => 'Délai livraison TOGO'],
            ['value' => '5+',   'label' => 'Pays desservis'],
            ['value' => '100%', 'label' => 'Taux de livraison réussie'],
        ],
    ],
    [
        'slug'        => 'conditionnement',
        'title'       => 'Conditionnement',
        'icon'        => 'flaticon-delivery-1',
        'image'       => '/assets/img/image12.jpg',
        'image2'      => '/assets/img/inner-page/service/service-details-01.jpg',
        'image3'      => '/assets/img/inner-page/service/service-details-02.jpg',
        'short'       => 'Conditionnement professionnel en sacs de 1kg, 5kg, 10kg et 25kg selon les besoins des clients.',
        'description' => 'Le conditionnement est une étape cruciale qui garantit la conservation et la présentation de nos produits riz. HEZOUWE propose plusieurs formats d\'emballage adaptés aux besoins des ménages, des restaurateurs et des revendeurs.',
        'description2'=> 'Nos emballages sont conçus pour préserver la fraîcheur du riz, résister à l\'humidité et permettre une conservation optimale. Chaque sac porte le logo HEZOUWE, le numéro de lot, la date de production et les informations nutritionnelles.',
        'steps' => [
            ['num' => '01', 'title' => 'Pesage de Précision', 'text' => 'Pesage automatisé garantissant le poids exact selon le format choisi.'],
            ['num' => '02', 'title' => 'Ensachage', 'text' => 'Mise en sac avec scellage hermétique pour une conservation optimale.'],
            ['num' => '03', 'title' => 'Étiquetage', 'text' => 'Apposition des étiquettes avec lot, date, certification et informations nutritionnelles.'],
            ['num' => '04', 'title' => 'Contrôle Final', 'text' => 'Vérification du poids, de l\'intégrité du sac et de l\'étiquetage avant expédition.'],
        ],
        'benefits' => [
            'Formats disponibles : 1kg, 5kg, 10kg et 25kg',
            'Emballages résistants à l\'humidité',
            'Étiquetage conforme aux normes alimentaires',
            'Possibilité de marquage personnalisé pour revendeurs',
            'Conditionnement sous atmosphère contrôlée',
            'Numéro de lot pour la traçabilité complète',
        ],
        'facts' => [
            ['value' => '4',    'label' => 'Formats disponibles'],
            ['value' => '100%', 'label' => 'Emballages hermétiques'],
            ['value' => '6 mois','label' => 'Durée de conservation'],
        ],
    ],
    [
        'slug'        => 'conseil',
        'title'       => 'Conseil Agricole',
        'icon'        => 'flaticon-manure',
        'image'       => '/assets/img/riz1.jpeg',
        'image2'      => '/assets/img/inner-page/service/service-details-02.jpg',
        'image3'      => '/assets/img/inner-page/service/service-details-03.jpg',
        'short'       => 'Accompagnement technique des producteurs pour améliorer les rendements et la qualité du riz local.',
        'description' => 'HEZOUWE met à la disposition de ses producteurs membres une équipe de techniciens agricoles spécialisés dans la culture du riz. Cet accompagnement vise à améliorer les rendements, réduire les pertes post-récolte et promouvoir des pratiques agricoles durables.',
        'description2'=> 'Les conseils portent sur la sélection des variétés, la gestion de l\'eau, la fertilisation raisonnée, la protection phytosanitaire et la mécanisation adaptée aux petites exploitations. Des formations régulières sont organisées sur le terrain.',
        'steps' => [
            ['num' => '01', 'title' => 'Diagnostic de l\'Exploitation', 'text' => 'Évaluation des pratiques actuelles et identification des axes d\'amélioration.'],
            ['num' => '02', 'title' => 'Plan d\'Action Personnalisé', 'text' => 'Élaboration d\'un programme d\'amélioration adapté à chaque producteur.'],
            ['num' => '03', 'title' => 'Formation & Démonstration', 'text' => 'Séances pratiques sur les techniques de culture et gestion post-récolte.'],
            ['num' => '04', 'title' => 'Suivi & Évaluation', 'text' => 'Accompagnement continu et mesure des progrès réalisés.'],
        ],
        'benefits' => [
            'Techniciens agricoles spécialisés en riziculture',
            'Formations pratiques sur le terrain',
            'Sélection de variétés à haut rendement',
            'Conseils en gestion durable de l\'eau',
            'Réduction des pertes post-récolte',
            'Accès aux intrants agricoles de qualité',
        ],
        'facts' => [
            ['value' => '30',   'label' => 'Producteurs accompagnés'],
            ['value' => '+40%', 'label' => 'Amélioration du rendement'],
            ['value' => '4',    'label' => 'Formations / an'],
        ],
    ],
    [
        'slug'        => 'support',
        'title'       => 'Support Commercial',
        'icon'        => 'flaticon-tractor',
        'image'       => '/assets/img/riz3.jpeg',
        'image2'      => '/assets/img/inner-page/service/service-details-01.jpg',
        'image3'      => '/assets/img/inner-page/service/service-details-03.jpg',
        'short'       => 'Support complet pour les commandes groupées, tarifs spéciaux et partenariats à long terme.',
        'description' => 'Notre équipe commerciale accompagne les revendeurs, grossistes, restaurants et institutions dans leurs achats de riz HEZOUWE. Des offres personnalisées sont proposées selon les volumes, avec des tarifs préférentiels pour les partenariats à long terme.',
        'description2'=> 'Nous offrons un service client réactif pour toutes vos demandes de devis, commandes personnalisées et informations sur nos produits. Un interlocuteur dédié est assigné à chaque partenaire commercial pour assurer un suivi personnalisé.',
        'steps' => [
            ['num' => '01', 'title' => 'Demande de Devis', 'text' => 'Soumission de votre besoin en volume et format pour un devis personnalisé.'],
            ['num' => '02', 'title' => 'Négociation & Accord', 'text' => 'Discussion des conditions tarifaires et signature d\'un accord commercial.'],
            ['num' => '03', 'title' => 'Traitement de la Commande', 'text' => 'Préparation et conditionnement de votre commande selon vos spécifications.'],
            ['num' => '04', 'title' => 'Livraison & Service Après-vente', 'text' => 'Livraison et suivi post-commande pour garantir votre satisfaction.'],
        ],
        'benefits' => [
            'Interlocuteur commercial dédié à chaque partenaire',
            'Tarifs dégressifs selon les volumes commandés',
            'Commandes minimum flexibles selon les formats',
            'Facturation et délais de paiement adaptés',
            'Disponibilité 6j/7 pour toutes vos demandes',
            'Contrats de fourniture à long terme disponibles',
        ],
        'facts' => [
            ['value' => '6j/7', 'label' => 'Disponibilité du support'],
            ['value' => '-15%', 'label' => 'Réduction commandes groupées'],
            ['value' => '48h',  'label' => 'Délai de réponse devis'],
        ],
    ],
    [
        'slug'        => 'formation',
        'title'       => 'Formation Produits',
        'icon'        => 'flaticon-cup',
        'image'       => '/assets/img/riz5.jpeg',
        'image2'      => '/assets/img/inner-page/service/service-details-01.jpg',
        'image3'      => '/assets/img/inner-page/service/service-details-02.jpg',
        'short'       => 'Formation et sensibilisation des clients sur les propriétés nutritionnelles et les usages de nos produits.',
        'description' => 'HEZOUWE organise régulièrement des sessions de formation et de sensibilisation destinées aux distributeurs, revendeurs, restaurateurs et consommateurs finaux. Ces formations couvrent les propriétés nutritionnelles du riz local, les modes de cuisson optimaux et les avantages du riz togolais.',
        'description2'=> 'Nos formateurs expliquent comment valoriser le riz local dans la cuisine togolaise traditionnelle et moderne, comment le différencier du riz importé, et comment communiquer ses avantages à la clientèle finale.',
        'steps' => [
            ['num' => '01', 'title' => 'Identification des Besoins', 'text' => 'Évaluation des connaissances actuelles et des besoins spécifiques du groupe.'],
            ['num' => '02', 'title' => 'Programme Adapté', 'text' => 'Conception d\'un programme de formation sur mesure selon le profil des participants.'],
            ['num' => '03', 'title' => 'Formation Pratique', 'text' => 'Sessions interactives incluant dégustations, démonstrations culinaires et ateliers.'],
            ['num' => '04', 'title' => 'Certification & Suivi', 'text' => 'Délivrance d\'une attestation de formation et suivi post-formation.'],
        ],
        'benefits' => [
            'Formations en présentiel et en ligne disponibles',
            'Supports de formation fournis (fiches, guides)',
            'Dégustations et démonstrations incluses',
            'Attestation de formation délivrée',
            'Formation adaptée aux revendeurs et restaurateurs',
            'Mise à jour régulière des contenus de formation',
        ],
        'facts' => [
            ['value' => '4+',  'label' => 'Sessions de formation / an'],
            ['value' => '200+','label' => 'Personnes formées'],
            ['value' => '100%','label' => 'Satisfaction des participants'],
        ],
    ],
];
